# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ace304fbcb9473d64e195aeabe6fd07a81b29fb22743232fe0e2debb7cee0f81c03d862e16046d932f7f11b461f4b3124fa8a005544d3f878ab175cdf97171f

test:
  secret_key_base: 40bac8482fbe5be281c47f9eee7463ae3926b915c7e9c6281a7b7a3b5c1a91371892e8ab03351dbcb5f6cd57e27d3db7c995133b627efef6c84387798feb5626

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
